// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy, Suspense } from 'react';
import { createBrowserRouter } from 'react-router-dom';
import { ErrorBoundary } from './components/ErrorBoundary';

const App = lazy(() => import('./pages/App'));
const About = lazy(() => import('./pages/About'));
const Services = lazy(() => import('./pages/Services'));
const Contact = lazy(() => import('./pages/Contact'));
const Portfolio = lazy(() => import('./pages/Portfolio'));

const LoadingFallback = () => (
  <div className="min-h-screen flex items-center justify-center bg-aurora-blue/5">
    <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-aurora-blue"></div>
  </div>
);

export const router = createBrowserRouter([
  {
    path: '/',
    element: (
      <Suspense fallback={<LoadingFallback />}>
        <App />
      </Suspense>
    ),
    errorElement: <ErrorBoundary />,
  },
  {
    path: '/about',
    element: (
      <Suspense fallback={<LoadingFallback />}>
        <About />
      </Suspense>
    ),
    errorElement: <ErrorBoundary />,
  },
  {
    path: '/services',
    element: (
      <Suspense fallback={<LoadingFallback />}>
        <Services />
      </Suspense>
    ),
    errorElement: <ErrorBoundary />,
  },
  {
    path: '/portfolio',
    element: (
      <Suspense fallback={<LoadingFallback />}>
        <Portfolio />
      </Suspense>
    ),
    errorElement: <ErrorBoundary />,
  },
  {
    path: '/contact',
    element: (
      <Suspense fallback={<LoadingFallback />}>
        <Contact />
      </Suspense>
    ),
    errorElement: <ErrorBoundary />,
  },
]);
